src/core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('', include('webapp.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "IMCCBAR site admin"

src/webapp/urls.py
from django.urls import path

from webapp import views

app_name = 'webapp'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about-center', views.AboutCenterView.as_view(), name='about_center'),
    path('organization-structure', views.OrgStructurePageView.as_view(), name='org_structure'),
    path('news', views.NewsListView.as_view(), name='news_list'),
    path('news/<int:pk>', views.NewsDetailView.as_view(), name='news_detail'),
    path('multimedia', views.MultimediaView.as_view(), name='media_list'),
    path('multimedia/photogallery/<int:pk>', views.PhotoGalleryDetailView.as_view(), name='album_detail'),
    path('multimedia/video/<int:pk>', views.VideDetailView.as_view(), name='video_detail'),
    path('cooperation-and-exchange', views.CooperationPageView.as_view(), name='cooperation_page'),
    path('platform-services', views.ServicesPageView.as_view(), name='platform_services'),
    path('faq', views.FAQPageView.as_view(), name='faq'),
    path('contacts', views.ContactsPageView.as_view(), name='contacts'),
    path('links', views.LinksPageView.as_view(), name='links'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]

src/webapp/models.py
from django.db import models
from django.core.validators import validate_image_file_extension, FileExtensionValidator
from ckeditor_uploader.fields import RichTextUploadingField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class News(models.Model):
    title = models.CharField(max_length=256)
    body = RichTextUploadingField()
    image = models.ImageField(upload_to='uploads/img/news/%Y/%m',
                              validators=[validate_image_file_extension])
    thumbnail = ImageSpecField(source='image',
                               processors=[ResizeToFill(825, 480)],
                               format='JPEG',
                               options={'quality': 100})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'

    def __str__(self):
        return self.title[:50]


class AboutCenterPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'About center'
        verbose_name_plural = 'About center'

    def __str__(self):
        return 'About center'


class AboutCenterPreview(models.Model):
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'About center preview'
        verbose_name_plural = 'About center preview'

    def __str__(self):
        return 'About center preview'


class OrgStructurePage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Organization structure'
        verbose_name_plural = 'Organization structure'

    def __str__(self):
        return 'Organization structure'


class OrgStructurePreview(models.Model):
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Organization structure preview'
        verbose_name_plural = 'Organization structure preview'

    def __str__(self):
        return 'Organization structure preview'


class PhotoAlbum(models.Model):
    title = models.CharField(max_length=255)
    poster = models.ImageField(upload_to='uploads/img/gallery/%Y/%m',
                               validators=[validate_image_file_extension])
    thumbnail = ImageSpecField(source='poster',
                               processors=[ResizeToFill(825, 480)],
                               format='JPEG',
                               options={'quality': 100})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Multimedia photo album'
        verbose_name_plural = 'Multimedia photo albums'

    def get_media_type(self):
        return 'photo'

    def __str__(self):
        return self.title[:30]


class PhotoAlbumImage(models.Model):
    image = models.ImageField(upload_to='uploads/img/gallery/%Y/%m',
                              validators=[validate_image_file_extension],
                              verbose_name='Photo')
    thumbnail = ImageSpecField(source='image',
                               processors=[ResizeToFill(825, 480)],
                               format='JPEG',
                               options={'quality': 100})
    album = models.ForeignKey('webapp.PhotoAlbum', related_name='images', on_delete=models.CASCADE,
                              verbose_name='Photo album')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Multimedia photo'
        verbose_name_plural = 'Multimedia photos'

    def __str__(self):
        return 'Multimedia photo'


class VideoItem(models.Model):
    title = models.CharField(max_length=255)
    poster = models.ImageField(upload_to='uploads/video/posters/%Y/%m',
                               validators=[validate_image_file_extension])
    thumbnail = ImageSpecField(source='poster',
                               processors=[ResizeToFill(825, 480)],
                               format='JPEG',
                               options={'quality': 100})
    file = models.FileField(
        upload_to='uploads/video/%Y/%m',
        validators=[FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Multimedia video'
        verbose_name_plural = 'Multimedia videos'

    def get_media_type(self):
        return 'video'

    def __str__(self):
        return self.title


class CooperationPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Cooperation and exchange'
        verbose_name_plural = 'Cooperation and exchange'

    def __str__(self):
        return 'Cooperation and exchange'


class ServicesPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Platform services'
        verbose_name_plural = 'Platform services'

    def __str__(self):
        return 'Platform services'


class FAQPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQ'

    def __str__(self):
        return 'FAQ'


class ContactsPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Contacts'
        verbose_name_plural = 'Contacts'

    def __str__(self):
        return 'Contacts'


class LinksPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Useful links'
        verbose_name_plural = 'Useful links'

    def __str__(self):
        return 'Useful links'

src/webapp/views/common_views.py
from itertools import chain
from operator import attrgetter

from django.utils.http import urlencode

from django.views.generic import TemplateView, ListView, DetailView

from core.settings import PAGINATION_COUNT
from webapp.models import News, AboutCenterPage, OrgStructurePage, PhotoAlbum, PhotoAlbumImage, \
    CooperationPage, ServicesPage, FAQPage, ContactsPage, LinksPage, AboutCenterPreview, \
    OrgStructurePreview, VideoItem


class HomeView(TemplateView):
    template_name = 'webapp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news'] = News.objects.all().order_by('-created_at')[:6]
        context['org_structure_preview'] = OrgStructurePreview.objects.first()
        context['about_center_preview'] = AboutCenterPreview.objects.first()
        photo_album = PhotoAlbum.objects.last()
        if photo_album:
            context['photo_album'] = photo_album
            context['photos'] = PhotoAlbumImage.objects.filter(album=photo_album)[:3]
        return context


class AboutCenterView(TemplateView):
    template_name = 'webapp/about-center.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['about'] = AboutCenterPage.objects.first()
        return context


class OrgStructurePageView(TemplateView):
    template_name = 'webapp/org-structure.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['org'] = OrgStructurePage.objects.first()
        return context


class MultimediaView(ListView):
    context_object_name = 'media_list'
    ordering = ['-created_at']
    template_name = 'webapp/multimedia-list.html'
    paginate_by = PAGINATION_COUNT

    def get_queryset(self):
        photo_albums = PhotoAlbum.objects.all()
        videos = VideoItem.objects.all()
        result_list = chain(photo_albums, videos)
        return sorted(result_list, key=attrgetter('created_at'), reverse=True)


class PhotoGalleryDetailView(DetailView):
    model = PhotoAlbum
    context_object_name = 'album'
    template_name = 'webapp/photo-album-detail.html'


class VideDetailView(DetailView):
    model = VideoItem
    context_object_name = 'video_item'
    template_name = 'webapp/video-detail.html'


class CooperationPageView(TemplateView):
    template_name = 'webapp/cooperation.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cooperation'] = CooperationPage.objects.first()
        return context


class ServicesPageView(TemplateView):
    template_name = 'webapp/services.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = ServicesPage.objects.first()
        return context


class FAQPageView(TemplateView):
    template_name = 'webapp/FAQ.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['faq'] = FAQPage.objects.first()
        return context


class ContactsPageView(TemplateView):
    template_name = 'webapp/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contacts'] = ContactsPage.objects.first()
        return context


class LinksPageView(TemplateView):
    template_name = 'webapp/links.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['links'] = LinksPage.objects.first()
        return context


class SearchResultsView(ListView):
    template_name = 'webapp/search-results.html'
    context_object_name = 'search_results'
    paginate_by = PAGINATION_COUNT

    def __init__(self):
        super().__init__()
        self.query = None

    def get_queryset(self):
        self.query = self.request.GET.get('q')
        if self.query and len(self.query) >= 2:
            news = News.objects.filter(title__icontains=self.query).order_by('-created_at')
            photoalbums = PhotoAlbum.objects.filter(title__icontains=self.query).order_by('-created_at')
            videos = VideoItem.objects.filter(title__icontains=self.query).order_by('-created_at')
            for n in news:
                n.model_type = 'news'
            for photoalbum in photoalbums:
                photoalbum.model_type = 'photo'
            for video in videos:
                video.model_type = 'video'
            return list(chain(news, photoalbums, videos))
        return News.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.query:
            context['query'] = urlencode({'q': self.query})
        return context

src/webapp/views/news_views.py
from django.views.generic import ListView, DetailView
from core.settings import PAGINATION_COUNT
from webapp.models import News


class NewsListView(ListView):
    model = News
    context_object_name = 'news'
    template_name = 'webapp/news/news-list.html'
    ordering = ['-created_at']
    paginate_by = PAGINATION_COUNT


class NewsDetailView(DetailView):
    model = News
    context_object_name = 'news_item'
    template_name = 'webapp/news/news-detail.html'

src/templates/webapp/partial/footer.html
{% load static %}
{% load i18n %}

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-9">
        <a href="/" class="logo">
          <span class="logo__img"><img src="{% static '/img/logo.png' %}" alt="IMCC"></span>
          <span class="logo__title">{% trans 'International Medical Cooperation Center for the Belt and Road' %}</span>
        </a>
      </div>
      <div class="col-12 col-md-3">
        <ul class="footer__menu">
          <li><a href="{% url 'webapp:faq' %}">{% trans 'Faq' %}</a></li>
          <li><a href="{% url 'webapp:contacts' %}">{% trans 'Contacts' %}</a></li>
          <li><a href="{% url 'webapp:links' %}">{% trans 'Links' %}</a></li>
        </ul>
        <div class="footer__icons">
          <a href="#" class="footer__icon footer__icon--instagram"></a>
          <a href="#" class="footer__icon footer__icon--facebook"></a>
          <a href="#" class="footer__icon footer__icon--youtube"></a>
        </div>
      </div>
      <span class="footer__copyright"> © 2022 {% trans 'All rights reserved' %}</span>
    </div>
  </div>
</footer>

src/templates/webapp/partial/header.html
{% load static %}
{% load i18n %}

<header class="header">
  <div class="header__top">
    <div class="container">
      <div class="lang">
        <form action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ redirect_to }}">
          <input type="hidden" name="language" value="zh-cn">
          <button type="submit" class="{% if LANG == 'zh-cn' %}active{% endif %}">中文</button>
        </form>
        <form action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ redirect_to }}">
          <input type="hidden" name="language" value="ru">
          <button type="submit" class="{% if LANG == 'ru' %}active{% endif %}">Рус</button>
        </form>
        <form action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ redirect_to }}">
          <input type="hidden" name="language" value="en">
          <button type="submit" class="{% if LANG == 'en' %}active{% endif %}">Eng</button>
        </form>
      </div>
    </div>
  </div>
  <div class="header__inner">
    <div class="container">
      <a href="/" class="logo">
        <span class="logo__img"><img src="{% static '/img/logo.png' %}" alt="IMCC"></span>
        <span class="logo__title">{% trans 'International Medical Cooperation Center for the Belt and Road' %}</span>
      </a>
      <div class="search-form">
        <form method="get" action="{% url 'webapp:search_results' %}">
          <div class="search-inp">
            <input name="q" type="text" minlength="2">
            <button type="submit"></button>
          </div>
        </form>
      </div>
    </div>
  </div>
</header>
<nav class="main-nav">
  <div class="container">
    <ul class="main-nav__list">
      <li><a href="{% url 'webapp:about_center' %}">{% trans 'About center' %}</a></li>
      <li><a href="{% url 'webapp:org_structure' %}">{% trans 'Organization' %}</a></li>
      <li><a href="{% url 'webapp:news_list' %}">{% trans 'News events' %}</a></li>
      <li><a href="{% url 'webapp:cooperation_page' %}">{% trans 'Cooperation and exchange' %}</a></li>
      <li><a href="{% url 'webapp:media_list' %}">{% trans 'Multimedia' %}</a></li>
      <li><a href="{% url 'webapp:platform_services' %}">{% trans 'Platform services' %}</a></li>
    </ul>
    <div class="menu-btn not-active" id="menu-btn"><span></span></div>
    <div class="search-form">
      <form method="get" action="{% url 'webapp:search_results' %}">
        <div class="search-inp">
          <input name="q" type="text" minlength="2">
          <button type="submit"></button>
        </div>
      </form>
    </div>
  </div>
</nav>

src/templates/webapp/partial/pagination.html
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% if page_obj.number|add:'-4' > 1 %}
            <li class="page-item"><a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
              </span>
                </li>
            {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                <li class="page-item"><a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>