src/core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('', include('webapp.urls'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "IMCCBAR site admin"

src/webapp/urls.py
from django.urls import path

from webapp import views

app_name = 'webapp'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about-center', views.AboutCenterView.as_view(), name='about_center'),
    path('organization-structure', views.OrgStructurePageView.as_view(), name='org_structure'),
    path('news', views.NewsListView.as_view(), name='news_list'),
    path('news/<int:pk>', views.NewsDetailView.as_view(), name='news_detail'),
    path('multimedia', views.MultimediaView.as_view(), name='media_list'),
    path('multimedia/photogallery/<int:pk>', views.PhotoGalleryDetailView.as_view(), name='album_detail'),
    path('multimedia/video/<int:pk>', views.VideDetailView.as_view(), name='video_detail'),
    path('cooperation-and-exchange', views.CooperationPageView.as_view(), name='cooperation_page'),
    path('platform-services', views.ServicesPageView.as_view(), name='platform_services'),
    path('faq', views.FAQPageView.as_view(), name='faq'),
    path('contacts', views.ContactsPageView.as_view(), name='contacts'),
    path('links', views.LinksPageView.as_view(), name='links'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]

src/webapp/models.py
from django.db import models
from django.core.validators import validate_image_file_extension, FileExtensionValidator
from ckeditor_uploader.fields import RichTextUploadingField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class News(models.Model):
    title = models.CharField(max_length=256)
    body = RichTextUploadingField()
    image = models.ImageField(upload_to='uploads/img/news/%Y/%m',
                              validators=[validate_image_file_extension])
    thumbnail = ImageSpecField(source='image',
                               processors=[ResizeToFill(825, 480)],
                               format='JPEG',
                               options={'quality': 100})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'

    def __str__(self):
        return self.title[:50]


class AboutCenterPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'About center'
        verbose_name_plural = 'About center'

    def __str__(self):
        return 'About center'


class AboutCenterPreview(models.Model):
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'About center preview'
        verbose_name_plural = 'About center preview'

    def __str__(self):
        return 'About center preview'


class OrgStructurePage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Organization structure'
        verbose_name_plural = 'Organization structure'

    def __str__(self):
        return 'Organization structure'


class OrgStructurePreview(models.Model):
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Organization structure preview'
        verbose_name_plural = 'Organization structure preview'

    def __str__(self):
        return 'Organization structure preview'


class PhotoAlbum(models.Model):
    title = models.CharField(max_length=255)
    poster = models.ImageField(upload_to='uploads/img/gallery/%Y/%m',
                               validators=[validate_image_file_extension])
    thumbnail = ImageSpecField(source='poster',
                               processors=[ResizeToFill(825, 480)],
                               format='JPEG',
                               options={'quality': 100})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Multimedia photo album'
        verbose_name_plural = 'Multimedia photo albums'

    def get_media_type(self):
        return 'photo'

    def __str__(self):
        return self.title[:30]


class PhotoAlbumImage(models.Model):
    image = models.ImageField(upload_to='uploads/img/gallery/%Y/%m',
                              validators=[validate_image_file_extension],
                              verbose_name='Photo')
    thumbnail = ImageSpecField(source='image',
                               processors=[ResizeToFill(825, 480)],
                               format='JPEG',
                               options={'quality': 100})
    album = models.ForeignKey('webapp.PhotoAlbum', related_name='images', on_delete=models.CASCADE,
                              verbose_name='Photo album')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Multimedia photo'
        verbose_name_plural = 'Multimedia photos'

    def __str__(self):
        return 'Multimedia photo'


class VideoItem(models.Model):
    title = models.CharField(max_length=255)
    poster = models.ImageField(upload_to='uploads/video/posters/%Y/%m',
                               validators=[validate_image_file_extension])
    thumbnail = ImageSpecField(source='poster',
                               processors=[ResizeToFill(825, 480)],
                               format='JPEG',
                               options={'quality': 100})
    file = models.FileField(
        upload_to='uploads/video/%Y/%m',
        validators=[FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Multimedia video'
        verbose_name_plural = 'Multimedia videos'

    def get_media_type(self):
        return 'video'

    def __str__(self):
        return self.title


class CooperationPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Cooperation and exchange'
        verbose_name_plural = 'Cooperation and exchange'

    def __str__(self):
        return 'Cooperation and exchange'


class ServicesPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Platform services'
        verbose_name_plural = 'Platform services'

    def __str__(self):
        return 'Platform services'


class FAQPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQ'

    def __str__(self):
        return 'FAQ'


class ContactsPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Contacts'
        verbose_name_plural = 'Contacts'

    def __str__(self):
        return 'Contacts'


class LinksPage(models.Model):
    body = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Useful links'
        verbose_name_plural = 'Useful links'

    def __str__(self):
        return 'Useful links'

src/webapp/views/common_views.py
from itertools import chain
from operator import attrgetter

from django.utils.http import urlencode

from django.views.generic import TemplateView, ListView, DetailView

from core.settings import PAGINATION_COUNT
from webapp.models import News, AboutCenterPage, OrgStructurePage, PhotoAlbum, PhotoAlbumImage, \
    CooperationPage, ServicesPage, FAQPage, ContactsPage, LinksPage, AboutCenterPreview, \
    OrgStructurePreview, VideoItem


class HomeView(TemplateView):
    template_name = 'webapp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news'] = News.objects.all().order_by('-created_at')[:6]
        context['org_structure_preview'] = OrgStructurePreview.objects.first()
        context['about_center_preview'] = AboutCenterPreview.objects.first()
        photo_album = PhotoAlbum.objects.last()
        if photo_album:
            context['photo_album'] = photo_album
            context['photos'] = PhotoAlbumImage.objects.filter(album=photo_album)[:3]
        return context


class AboutCenterView(TemplateView):
    template_name = 'webapp/about-center.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['about'] = AboutCenterPage.objects.first()
        return context


class OrgStructurePageView(TemplateView):
    template_name = 'webapp/org-structure.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['org'] = OrgStructurePage.objects.first()
        return context


class MultimediaView(ListView):
    context_object_name = 'media_list'
    ordering = ['-created_at']
    template_name = 'webapp/multimedia-list.html'
    paginate_by = PAGINATION_COUNT

    def get_queryset(self):
        photo_albums = PhotoAlbum.objects.all()
        videos = VideoItem.objects.all()
        result_list = chain(photo_albums, videos)
        return sorted(result_list, key=attrgetter('created_at'), reverse=True)


class PhotoGalleryDetailView(DetailView):
    model = PhotoAlbum
    context_object_name = 'album'
    template_name = 'webapp/photo-album-detail.html'


class VideDetailView(DetailView):
    model = VideoItem
    context_object_name = 'video_item'
    template_name = 'webapp/video-detail.html'


class CooperationPageView(TemplateView):
    template_name = 'webapp/cooperation.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cooperation'] = CooperationPage.objects.first()
        return context


class ServicesPageView(TemplateView):
    template_name = 'webapp/services.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = ServicesPage.objects.first()
        return context


class FAQPageView(TemplateView):
    template_name = 'webapp/FAQ.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['faq'] = FAQPage.objects.first()
        return context


class ContactsPageView(TemplateView):
    template_name = 'webapp/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contacts'] = ContactsPage.objects.first()
        return context


class LinksPageView(TemplateView):
    template_name = 'webapp/links.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['links'] = LinksPage.objects.first()
        return context


class SearchResultsView(ListView):
    template_name = 'webapp/search-results.html'
    context_object_name = 'search_results'
    paginate_by = PAGINATION_COUNT

    def __init__(self):
        super().__init__()
        self.query = None

    def get_queryset(self):
        self.query = self.request.GET.get('q')
        if self.query and len(self.query) >= 2:
            news = News.objects.filter(title__icontains=self.query).order_by('-created_at')
            photoalbums = PhotoAlbum.objects.filter(title__icontains=self.query).order_by('-created_at')
            videos = VideoItem.objects.filter(title__icontains=self.query).order_by('-created_at')
            for n in news:
                n.model_type = 'news'
            for photoalbum in photoalbums:
                photoalbum.model_type = 'photo'
            for video in videos:
                video.model_type = 'video'
            return list(chain(news, photoalbums, videos))
        return News.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.query:
            context['query'] = urlencode({'q': self.query})
        return context

src/webapp/views/news_views.py
from django.views.generic import ListView, DetailView
from core.settings import PAGINATION_COUNT
from webapp.models import News


class NewsListView(ListView):
    model = News
    context_object_name = 'news'
    template_name = 'webapp/news/news-list.html'
    ordering = ['-created_at']
    paginate_by = PAGINATION_COUNT


class NewsDetailView(DetailView):
    model = News
    context_object_name = 'news_item'
    template_name = 'webapp/news/news-detail.html'

src/templates/webapp/FAQ.html
{% extends 'webapp/base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <div class="detail-page">
      <h1 class="section-title">{% trans 'Frequently Asked Questions' %}</h1>
      {{ faq.body | safe }}
    </div>
  </div>
{% endblock %}

src/templates/webapp/about-center.html
{% extends 'webapp/base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <div class="detail-page">
      <h1 class="section-title">{% trans 'International Medical Cooperation Center for the Belt and Road' %}</h1>
      {{ about.body | safe }}
    </div>
  </div>
{% endblock %}

src/templates/webapp/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANG %}


<!doctype html>
<html lang="{{ LANG }}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
 <meta name="description" content="International Medical Cooperation Center for the Belt and Road, IMCCBAR">
  <title>{% trans 'International Medical Cooperation Center for the Belt and Road' %}</title>
  {% block css %}{% endblock %}
  <link rel="stylesheet" href="{% static '/css/bootstrap-reboot.css' %}">
  <link rel="stylesheet" href="{% static '/css/bootstrap-grid.css' %}">
  <link rel="stylesheet" href="{% static '/css/fonts.css' %}">
  <link rel="stylesheet" href="{% static '/css/main.css' %}">
  <link rel="icon" href="{% static '/img/logo.png' %}" type="image/x-png">

  <meta property="og:title" content="{% trans 'International Medical Cooperation Center for the Belt and Road' %}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://imccbar.org/">
  <meta property="og:image" content="https://imccbar.org/static/img/og-logo.jpg">
  <meta property="og:image:height" content="200">
  <meta property="og:image:width" content="200">
  <meta property="og:description" content="{% trans 'International Medical Cooperation Center for the Belt and Road' %}">
  <meta property="og:locale" content="{{ LANG }}">
</head>
<body style="font-family: {% if LANG == 'zh-cn' %}'Noto Sans SC'{% else %}'Roboto'{% endif %}, sans-serif;">
<div class="wrapper">
  <div class="main">
    {% include 'webapp/partial/header.html' %}
    <div class="py-5">
      {% block content %}{% endblock %}
    </div>
  </div>
  {% include 'webapp/partial/footer.html' %}
</div>

  <script src="{% static '/js/jquery-3.6.0.min.js'%}"></script>
  {% block js %}{% endblock %}
  <script src="{% static '/js/main.js' %}"></script>
</body>
</html>

src/templates/webapp/contacts.html
{% extends 'webapp/base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
  <div class="container">
    <h1 class="section-title">{% trans 'Contacts' %}</h1>
    {{ contacts.body | safe }}
    <div class="pt-3">
      <div class="map" id="map"></div>
    </div>
  </div>
{% endblock %}

{% block js %}
  <script src="https://api-maps.yandex.ru/2.1/?lang={{ LANG }}" type="text/javascript"></script>
  <script>
    ymaps.ready(init);

    function init() {
      const myMap = new ymaps.Map("map", {
        center: [42.868, 74.604],
        zoom: 14,
        controls: ['zoomControl'],
        behaviors: ['drag', 'multiTouch']
      });

      const placeMark = new ymaps.Placemark([42.868569, 74.604429], {
            balloonContent: '{% trans 'International Medical Cooperation Center for the Belt and Road' %}',
          },
          {
            iconLayout: 'default#image',
            iconImageHref: '{% static 'img/imcc-marker.png' %}',
            hideIconOnBalloonOpen: false,
            iconImageSize: [48, 60],
            iconImageOffset: [-26, -60],
            balloonOffset: [0, -56]
          });

      myMap.geoObjects.add(placeMark);
    }
  </script>
{% endblock %}

src/templates/webapp/cooperation.html
{% extends 'webapp/base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <div class="detail-page">
      <h1 class="section-title">{% trans 'Cooperation and exchange' %}</h1>
      {{ cooperation.body | safe }}
    </div>
  </div>
{% endblock %}

src/templates/webapp/index.html
{% extends 'webapp/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
  {% include 'webapp/news/home-news-section.html' %}
  <div class="home-map"></div>

  <div class="home-about">
    <div class="container">
      <a href="{% url 'webapp:about_center' %}" class="logo">
        <span class="logo__img"><img src="{% static '/img/logo.png' %}" alt="IMCC"></span>
        <span class="logo__title">{% trans 'International Medical Cooperation Center for the Belt and Road' %}</span>
      </a>
      <div class="row">
        <div class="col-12 col-lg-12">
          <p>{{ about_center_preview.body }}</p>
        </div>
      </div>
    </div>
  </div>

  <div class="home-org-structure">
    <div class="home-org-structure__inner">
      <div class="container">
        <div class="row">
          <div class="col-12 col-lg-5">
            <div class="home-org-structure__info">
              <h2 class="section-title">{% trans 'Organization structure' %}</h2>
              <p class="home-org-structure__descr">{{ org_structure_preview.body }}</p>
              <a href="{% url 'webapp:org_structure' %}" class="link-btn">{% trans 'Read more' %}</a>
            </div>
          </div>
          <div class="col-12 col-lg-7">
            <div class="row">
              <div class="col-12 col-md-6">
                <div class="home-org-structure__item">
                  <span class="home-org-structure__item-num">1</span>
                  <span class="home-org-structure__item-label">{% trans 'Advisory Committee' %}</span>
                </div>
              </div>
              <div class="col-12 col-md-6">
                <div class="home-org-structure__item">
                  <span class="home-org-structure__item-num">2</span>
                  <span class="home-org-structure__item-label">{% trans 'Experts Committee' %}</span>
                </div>
              </div>
              <div class="col-12 col-md-6">
                <div class="home-org-structure__item">
                  <span class="home-org-structure__item-num">3</span>
                  <span class="home-org-structure__item-label">{% trans 'Administrative Council' %}</span>
                </div>
              </div>
              <div class="col-12 col-md-6">
                <div class="home-org-structure__item">
                  <span class="home-org-structure__item-num">4</span>
                  <span class="home-org-structure__item-label">{% trans 'Permanent Establishment' %}</span>
                </div>
              </div>
            </div>
            <div class="home-org-structure__readmore">
              <a href="{% url 'webapp:org_structure' %}" class="link-btn">{% trans 'Read more' %}</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if photo_album %}
    <div class="multimedia-tab">
      <div class="container">
        <h2 class="section-title">{% trans 'Multimedia' %}</h2>
        <div class="row">
          <div class="col-12 col-lg-2">
            <div class="multimedia-tab__links">
              {% for photo in photos %}
                <div class="multimedia-tab__link {% if forloop.counter == 1 %}active{% endif %}">
                  <img src="{{ photo.thumbnail.url }}" alt="{{ photo_album.title }}">
                </div>
              {% endfor %}
            </div>
          </div>
          <div class="col-12 col-lg-10">
            {% for photo in photos %}
              <div class="multimedia-tab__content">
                <a href="{% url 'webapp:album_detail' photo_album.pk %}"
                   class="multimedia-tab__content-img">
                  <img src="{{ photo.thumbnail.url }}" alt="{{ photo_album.title }}">
                </a>
              </div>
            {% endfor %}
            <h3 class="multimedia-tab__content-title">
              <a href="{% url 'webapp:album_detail' photo_album.pk %}">{{ photo_album.title }}</a>
            </h3>
            <span class="multimedia-tab__content-date">{{ photo_album.created_at | date:'Y / m / d' }}</span>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

src/templates/webapp/links.html
{% extends 'webapp/base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <div class="detail-page">
      <h1 class="section-title">{% trans 'Links' %}</h1>
      {{ links.body | safe }}
    </div>
  </div>
{% endblock %}

src/templates/webapp/multimedia-list.html
{% extends 'webapp/base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <h1 class="section-title">{% trans 'Multimedia' %}</h1>
    <div class="row">
      {% for media_item in media_list %}
        <div class="col-12 col-lg-4">
          {% if media_item.get_media_type == 'photo' %}
            <div class="news-card news-card--photogallery">
              <a href="{% url 'webapp:album_detail' media_item.pk %}" class="news-card__img">
                <img src="{{ media_item.thumbnail.url }}" alt="{{ media_item.title }}">
              </a>
              <div class="news-card__body">
                <h3 class="news-card__title">
                  <a href="{% url 'webapp:album_detail' media_item.pk %}">{{ media_item.title }}</a>
                </h3>
                <span class="news-card__date">{{ media_item.created_at | date:'Y / m / d' }}</span>
              </div>
            </div>
          {% elif media_item.get_media_type == 'video' %}
            <div class="news-card news-card--video">
              <a href="{% url 'webapp:video_detail' media_item.pk %}" class="news-card__img">
                <img src="{{ media_item.thumbnail.url }}" alt="{{ media_item.title }}">
              </a>
              <div class="news-card__body">
                <h3 class="news-card__title">
                  <a href="{% url 'webapp:video_detail' media_item.pk %}">{{ media_item.title }}</a>
                </h3>
                <span class="news-card__date">{{ media_item.created_at | date:'Y / m / d' }}</span>
              </div>
            </div>
          {% endif %}
        </div>
      {% endfor %}
    </div>
    {% if is_paginated %}
      {% include 'webapp/partial/pagination.html' %}
    {% endif %}
  </div>
{% endblock %}

src/templates/webapp/org-structure.html
{% extends 'webapp/base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <div class="detail-page">
      <h1 class="section-title">{% trans 'Organization structure' %}</h1>
      {{ org.body | safe }}
    </div>
  </div>
{% endblock %}

src/templates/webapp/photo-album-detail.html
{% extends 'webapp/base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static '/css/jquery.fancybox.min.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="section-title">{{ album.title }}</h1>
    <div class="row">
      {% for image in  album.images.all %}
        <div class="col-6 col-md-4 col-lg-3">
          <a class="gallery-img" href="{{ image.image.url }}" data-fancybox="img">
            <img src="{{ image.thumbnail.url }}" alt="{{ image.title }}"/>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block js %}
  <script src="{% static '/js/jquery.fancybox.min.js' %}"></script>
  <script>
    $(document).ready(function () {
      $('[data-fancybox="img"]').fancybox({
        buttons: [
          //"zoom",
          //"share",
          "slideShow",
          //"fullScreen",
          //"download",
          //"thumbs",
          "close"
        ],
      });
    });
  </script>
{% endblock %}

src/templates/webapp/search-results.html
{% extends 'webapp/base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <div class="detail-page">
      <h1 class="section-title">{% trans 'Search results' %}</h1>

      {% if search_results %}
        {% regroup search_results by model_type as results %}
        {% for type in results %}
          {% if type.grouper == 'news' %}
            <div class="mb-3">
              <h3>{% trans 'News' %}</h3>
            </div>
          {% elif type.grouper == 'photo' or type.grouper == 'video' %}
            <div class="mb-3">
              <h3>{% trans 'Multimedia' %}</h3>
            </div>
          {% endif %}
          <div class="mb-4">
            {% for result in type.list %}
              {% if type.grouper == 'news' %}
                <div class="mb-2">
                  <a href="{% url 'webapp:news_detail' result.pk %}">{{ result.title }}</a>
                </div>
              {% elif type.grouper == 'photo' %}
                <div class="mb-2">
                  <a href="{% url 'webapp:album_detail' result.pk %}">{{ result.title }}</a>
                </div>
              {% elif type.grouper == 'video' %}
                <div class="mb-2">
                  <a href="{% url 'webapp:video_detail' result.pk %}">{{ result.title }}</a>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        {% endfor %}
      {% else %}
        <p class="text-center">{% trans 'No matches found' %}</p>
      {% endif %}

      {% if is_paginated %}
        {% include 'webapp/partial/pagination.html' %}
      {% endif %}
    </div>
  </div>
{% endblock %}

src/templates/webapp/services.html
{% extends 'webapp/base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <div class="detail-page">
      <h1 class="section-title">{% trans 'Platform services' %}</h1>
      {{ services.body | safe }}
    </div>
  </div>
{% endblock %}

src/templates/webapp/video-detail.html
{% extends 'webapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="detail-page">
      <h1 class="section-title">{{ video_item.title }}</h1>
      <video id="media-video"
             class="video-js"
             controls
             preload="auto"
             width="100%"
             height="auto"
             poster="{{ video_item.thumbnail.url }}"
             data-setup="{}"
      >
        <source src="{{ video_item.file.url }}" />
      </video>
    </div>
  </div>
{% endblock %}